### ISSUE TITLE
Recording for Components on a grid

### ISSUE THREAD

**Issue by EmmaJLussier** [EmmaJLussier/components-on-a-grid#3]
[Reading css.zip](https://github.com/EmmaJLussier/components-on-a-grid/files/7220700/Reading.css.zip)

**Comment by EmmaJLussier** [comment]
@thatkidmadrid

**Comment by thatkidmadrid** [comment]
Looks good and sounds good!
you're saying `selector tag` a bunch which is fine, but would also be find to not say `tag`

for example:
```
h2 { 
...
}
```
you can say `select h2 ...`
